export const Images = {
  backgroundLogged: require('../assets/images/background.jpeg'),
  avatar: require('../assets/images/avatar.jpeg'),
  add: require('../assets/icons/add.png'),
  story1: require('../assets/images/story1.jpeg'),
  story2: require('../assets/images/story2.jpeg'),
  story3: require('../assets/images/story3.jpeg'),
  story4: require('../assets/images/story4.jpeg'),
  avatar1: require('../assets/images/avatar1.jpeg'),
  avatar2: require('../assets/images/avatar2.jpeg'),
  avatar3: require('../assets/images/avatar3.jpeg'),
  avatar4: require('../assets/images/avatar4.jpeg'),
  image1: require('../assets/images/image1.jpeg'),
  image2: require('../assets/images/image2.jpeg'),
  image3: require('../assets/images/image3.jpeg'),
  image4: require('../assets/images/image4.jpeg'),
  image5: require('../assets/images/image5.jpeg'),
  image6: require('../assets/images/image6.jpeg'),
  image7: require('../assets/images/image7.jpeg'),
  image8: require('../assets/images/image8.jpeg'),
  image9: require('../assets/images/image9.jpeg'),
  image10: require('../assets/images/image10.jpeg'),
}